/**
 * Auto-generated by Portcall CLI
 * Generated at: 2026-01-19T16:23:39.213Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npx portcall generate' to regenerate
 */

import axios, { AxiosInstance } from "axios";

// =============================================================================
// Types
// =============================================================================

export type PlanName = "e2eTestPlan" | "proPlan" | "testPlanViaApi" | "newQuote_1" | "newQuote_2" | "newQuote_3" | "newQuote_4" | "newQuote_5";
export type PlanId = "plan_7afaeb0ab81f41dcaa1eb386947cd76e" | "plan_47b96a6970ed404c9acdf4114ae77932" | "plan_d573874400184f9e8b512e6073ed4b9b" | "plan_a1f47aafaf5a4b1ba3f34c7d4e90f2a2" | "plan_7271d65bcd704d0dbcf54ba0c6512161" | "plan_81b72618c1954f2895017e496c578ac1" | "plan_d2716f54d93549378f1eb3445ec44d92" | "plan_7cf9421a41db4380b660d0588ea49941";
export type FeatureId = "e2e_feature" | "premium_support" | "api_calls" | "tokens";

export interface PortcallClientConfig {
  apiKey: string;
  baseURL?: string;
}

export interface User {
  id: string;
  email: string;
  name?: string;
  created_at: string;
  updated_at: string;
}

export interface Subscription {
  id: string;
  user_id: string;
  plan_id: string;
  status: "active" | "canceled" | "past_due" | "trialing" | "incomplete";
  current_period_start?: string;
  current_period_end?: string;
  cancel_at_period_end?: boolean;
  created_at: string;
  updated_at: string;
}

export interface Entitlement {
  id: string;
  usage: number;
  quota: number;
  interval: string;
  enabled: boolean;
  next_reset_at?: string;
  created_at: string;
  updated_at: string;
}

export interface CheckoutSession {
  id: string;
  url: string;
  client_secret: string;
  expires_at: string;
}

export interface Plan {
  id: string;
  name: string;
  status: string;
  currency: string;
  interval: string;
  interval_count: number;
  trial_period_days: number;
}

// =============================================================================
// Constants
// =============================================================================

/**
 * All plan IDs in your Portcall app
 */
export const PLANS = {
  E2E_TEST_PLAN: "plan_7afaeb0ab81f41dcaa1eb386947cd76e",
  PRO_PLAN: "plan_47b96a6970ed404c9acdf4114ae77932",
  TEST_PLAN_VIA_API: "plan_d573874400184f9e8b512e6073ed4b9b",
  NEW_QUOTE_1: "plan_a1f47aafaf5a4b1ba3f34c7d4e90f2a2",
  NEW_QUOTE_2: "plan_7271d65bcd704d0dbcf54ba0c6512161",
  NEW_QUOTE_3: "plan_81b72618c1954f2895017e496c578ac1",
  NEW_QUOTE_4: "plan_d2716f54d93549378f1eb3445ec44d92",
  NEW_QUOTE_5: "plan_7cf9421a41db4380b660d0588ea49941",
} as const;

/**
 * All feature IDs in your Portcall app
 */
export const FEATURES = {
  E2E_FEATURE: "e2e_feature",
  PREMIUM_SUPPORT: "premium_support",
  API_CALLS: "api_calls",
  TOKENS: "tokens",
} as const;

// =============================================================================
// Plan Helper Class
// =============================================================================

class PlanHelper {
  constructor(
    private http: AxiosInstance,
    public readonly id: PlanId,
    public readonly name: string
  ) {}

  /**
   * Create a checkout session for a user to subscribe to this plan.
   * Creates the user if they don't exist.
   */
  async subscribe(
    email: string,
    options?: {
      name?: string;
      cancelUrl?: string;
      redirectUrl?: string;
    }
  ): Promise<CheckoutSession> {
    // First, find or create the user
    const user = await this.findOrCreateUser(email, options?.name);

    // Create checkout session
    const response = await this.http.post<{ data: CheckoutSession }>("/v1/checkout-sessions", {
      plan_id: this.id,
      user_id: user.id,
      cancel_url: options?.cancelUrl || `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000'}?status=canceled`,
      redirect_url: options?.redirectUrl || `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000'}?status=success`,
    });

    return response.data.data || response.data;
  }

  /**
   * Get details about this plan
   */
  async get(): Promise<Plan> {
    const response = await this.http.get<{ data: Plan }>(`/v1/plans/${this.id}`);
    return response.data.data || response.data;
  }

  private async findOrCreateUser(email: string, name?: string): Promise<User> {
    // Try to find existing user
    const listResponse = await this.http.get<{ data: User[] }>(`/v1/users?email=${encodeURIComponent(email)}`);
    const users = listResponse.data.data || listResponse.data || [];
    
    if (users.length > 0) {
      return users[0];
    }

    // Create new user
    const createResponse = await this.http.post<{ data: User }>("/v1/users", {
      email,
      name: name || email.split("@")[0],
    });

    return createResponse.data.data || createResponse.data;
  }
}

// =============================================================================
// Entitlement Helper Class
// =============================================================================

class EntitlementHelper {
  constructor(
    private http: AxiosInstance,
    public readonly id: FeatureId
  ) {}

  /**
   * Check if a user has this entitlement enabled
   */
  async isEnabled(userIdOrEmail: string): Promise<boolean> {
    try {
      const userId = await this.resolveUserId(userIdOrEmail);
      const entitlement = await this.get(userId);
      return entitlement.enabled;
    } catch {
      return false;
    }
  }

  /**
   * Check if a user can use this feature (alias for isEnabled)
   */
  async canUse(userIdOrEmail: string): Promise<boolean> {
    return this.isEnabled(userIdOrEmail);
  }

  /**
   * Check if a user has access to this feature (alias for isEnabled)
   */
  async hasAccess(userIdOrEmail: string): Promise<boolean> {
    return this.isEnabled(userIdOrEmail);
  }

  /**
   * Get the full entitlement details for a user
   */
  async get(userIdOrEmail: string): Promise<Entitlement> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Entitlement }>(
      `/v1/entitlements/${userId}/${this.id}`
    );
    return response.data.data || response.data;
  }

  /**
   * Get remaining quota for a metered feature
   */
  async getRemaining(userIdOrEmail: string): Promise<number> {
    const entitlement = await this.get(userIdOrEmail);
    if (entitlement.quota === -1) {
      return Infinity; // Unlimited
    }
    return Math.max(0, entitlement.quota - entitlement.usage);
  }

  /**
   * Get usage for a metered feature
   */
  async getUsage(userIdOrEmail: string): Promise<{ usage: number; quota: number; remaining: number }> {
    const entitlement = await this.get(userIdOrEmail);
    const remaining = entitlement.quota === -1 ? Infinity : Math.max(0, entitlement.quota - entitlement.usage);
    return {
      usage: entitlement.usage,
      quota: entitlement.quota,
      remaining,
    };
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    // If it looks like an email, look up the user
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Meter Events Helper Class
// =============================================================================

class MeterEventsHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Record usage for a metered feature
   */
  async record(
    userIdOrEmail: string,
    featureId: FeatureId,
    usage: number = 1
  ): Promise<void> {
    const userId = await this.resolveUserId(userIdOrEmail);
    await this.http.post("/v1/meter-events", {
      user_id: userId,
      feature_id: featureId,
      usage,
    });
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Users Helper Class
// =============================================================================

class UsersHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Get a user by email
   */
  async getByEmail(email: string): Promise<User | null> {
    const response = await this.http.get<{ data: User[] }>(
      `/v1/users?email=${encodeURIComponent(email)}`
    );
    const users = response.data.data || response.data || [];
    return users[0] || null;
  }

  /**
   * Get a user by ID
   */
  async get(userId: string): Promise<User> {
    const response = await this.http.get<{ data: User }>(`/v1/users/${userId}`);
    return response.data.data || response.data;
  }

  /**
   * Create a new user
   */
  async create(data: { email: string; name?: string }): Promise<User> {
    const response = await this.http.post<{ data: User }>("/v1/users", data);
    return response.data.data || response.data;
  }

  /**
   * Find or create a user by email
   */
  async findOrCreate(email: string, name?: string): Promise<User> {
    const existing = await this.getByEmail(email);
    if (existing) {
      return existing;
    }
    return this.create({ email, name: name || email.split("@")[0] });
  }
}

// =============================================================================
// Subscriptions Helper Class
// =============================================================================

class SubscriptionsHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Get active subscription for a user
   */
  async getActive(userIdOrEmail: string): Promise<Subscription | null> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Subscription[] }>(
      `/v1/subscriptions?user_id=${userId}&status=active&limit=1`
    );
    const subscriptions = response.data.data || response.data || [];
    return subscriptions[0] || null;
  }

  /**
   * List all subscriptions for a user
   */
  async list(userIdOrEmail: string): Promise<Subscription[]> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Subscription[] }>(
      `/v1/subscriptions?user_id=${userId}`
    );
    return response.data.data || response.data || [];
  }

  /**
   * Cancel a subscription
   */
  async cancel(subscriptionId: string, immediately: boolean = false): Promise<Subscription> {
    const response = await this.http.post<{ data: Subscription }>(
      `/v1/subscriptions/${subscriptionId}/cancel`,
      { immediately }
    );
    return response.data.data || response.data;
  }

  /**
   * Update a subscription (e.g., change plan)
   */
  async update(subscriptionId: string, data: { plan_id?: PlanId }): Promise<Subscription> {
    const response = await this.http.post<{ data: Subscription }>(
      `/v1/subscriptions/${subscriptionId}`,
      data
    );
    return response.data.data || response.data;
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Plans Manager Class (CRUD operations)
// =============================================================================

interface CreatePlanParams {
  name: string;
  currency?: string;
  interval?: "day" | "week" | "month" | "year";
  interval_count?: number;
  trial_period_days?: number;
  unit_amount?: number;
}

interface UpdatePlanParams {
  name?: string;
  currency?: string;
  interval?: "day" | "week" | "month" | "year";
  interval_count?: number;
  trial_period_days?: number;
  unit_amount?: number;
}

interface AddFeatureParams {
  plan_id: string;
  feature_id: string;
  interval?: "day" | "week" | "month" | "year";
  quota?: number;
}

interface PlanFeature {
  id: string;
  feature?: string;
  interval?: string;
  quota?: number;
  created_at: string;
  updated_at: string;
}

class PlansManager {
  constructor(private http: AxiosInstance) {}

  /**
   * List all plans
   */
  async list(): Promise<Plan[]> {
    const response = await this.http.get<{ data: Plan[] }>("/v1/plans");
    return response.data.data || response.data || [];
  }

  /**
   * Get a plan by ID
   */
  async get(planId: string): Promise<Plan> {
    const response = await this.http.get<{ data: Plan }>(`/v1/plans/${planId}`);
    return response.data.data || response.data;
  }

  /**
   * Create a new plan
   */
  async create(data: CreatePlanParams): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>("/v1/plans", data);
    return response.data.data || response.data;
  }

  /**
   * Update a plan
   */
  async update(planId: string, data: UpdatePlanParams): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>(`/v1/plans/${planId}`, data);
    return response.data.data || response.data;
  }

  /**
   * Publish a plan (make it available for subscriptions)
   */
  async publish(planId: string): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>(`/v1/plans/${planId}/publish`, {});
    return response.data.data || response.data;
  }

  /**
   * Add a feature to a plan
   */
  async addFeature(data: AddFeatureParams): Promise<PlanFeature> {
    const response = await this.http.post<{ data: PlanFeature }>("/v1/plan-features", data);
    return response.data.data || response.data;
  }

  /**
   * List features for a plan
   */
  async listFeatures(planId: string): Promise<PlanFeature[]> {
    const response = await this.http.get<{ data: PlanFeature[] }>(`/v1/plan-features?plan_id=${planId}`);
    return response.data.data || response.data || [];
  }
}

// =============================================================================
// Features Manager Class (CRUD operations)
// =============================================================================

interface CreateFeatureParams {
  feature_id: string;
  is_metered?: boolean;
}

interface Feature {
  id: string;
  is_metered: boolean;
  created_at: string;
  updated_at: string;
}

class FeaturesManager {
  constructor(private http: AxiosInstance) {}

  /**
   * List all features
   */
  async list(params?: { is_metered?: boolean }): Promise<Feature[]> {
    let url = "/v1/features";
    if (params?.is_metered !== undefined) {
      url += `?is_metered=${params.is_metered}`;
    }
    const response = await this.http.get<{ data: Feature[] }>(url);
    return response.data.data || response.data || [];
  }

  /**
   * List all non-metered (boolean) features
   */
  async listStandard(): Promise<Feature[]> {
    return this.list({ is_metered: false });
  }

  /**
   * List all metered features
   */
  async listMetered(): Promise<Feature[]> {
    return this.list({ is_metered: true });
  }

  /**
   * Create a new feature
   */
  async create(data: CreateFeatureParams): Promise<Feature> {
    const response = await this.http.post<{ data: Feature }>("/v1/features", data);
    return response.data.data || response.data;
  }
}

// =============================================================================
// Generated Plan Helpers
// =============================================================================

/**
 * E2E Test Plan plan helper
 * ID: plan_7afaeb0ab81f41dcaa1eb386947cd76e
 * Status: published
 */
function createE2eTestPlanPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_7afaeb0ab81f41dcaa1eb386947cd76e", "E2E Test Plan");
}

/**
 * Pro Plan plan helper
 * ID: plan_47b96a6970ed404c9acdf4114ae77932
 * Status: draft
 */
function createProPlanPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_47b96a6970ed404c9acdf4114ae77932", "Pro Plan");
}

/**
 * Test Plan via API plan helper
 * ID: plan_d573874400184f9e8b512e6073ed4b9b
 * Status: published
 */
function createTestPlanViaApiPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_d573874400184f9e8b512e6073ed4b9b", "Test Plan via API");
}

/**
 * New Quote plan helper
 * ID: plan_a1f47aafaf5a4b1ba3f34c7d4e90f2a2
 * Status: draft
 */
function createNewQuote_1Plan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_a1f47aafaf5a4b1ba3f34c7d4e90f2a2", "New Quote");
}

/**
 * New Quote plan helper
 * ID: plan_7271d65bcd704d0dbcf54ba0c6512161
 * Status: init
 */
function createNewQuote_2Plan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_7271d65bcd704d0dbcf54ba0c6512161", "New Quote");
}

/**
 * New Quote plan helper
 * ID: plan_81b72618c1954f2895017e496c578ac1
 * Status: init
 */
function createNewQuote_3Plan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_81b72618c1954f2895017e496c578ac1", "New Quote");
}

/**
 * New Quote plan helper
 * ID: plan_d2716f54d93549378f1eb3445ec44d92
 * Status: init
 */
function createNewQuote_4Plan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_d2716f54d93549378f1eb3445ec44d92", "New Quote");
}

/**
 * New Quote plan helper
 * ID: plan_7cf9421a41db4380b660d0588ea49941
 * Status: published
 */
function createNewQuote_5Plan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_7cf9421a41db4380b660d0588ea49941", "New Quote");
}

// =============================================================================
// Generated Entitlement Helpers  
// =============================================================================

/**
 * e2e_feature entitlement helper
 * Metered: false
 */
function createE2eFeatureEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "e2e_feature");
}

/**
 * premium_support entitlement helper
 * Metered: false
 */
function createPremiumSupportEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "premium_support");
}

/**
 * api_calls entitlement helper
 * Metered: true
 */
function createApiCallsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "api_calls");
}

/**
 * tokens entitlement helper
 * Metered: true
 */
function createTokensEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "tokens");
}

// =============================================================================
// Main Client Types
// =============================================================================

export interface PortcallPlans {
  e2eTestPlan: PlanHelper;
  proPlan: PlanHelper;
  testPlanViaApi: PlanHelper;
  newQuote_1: PlanHelper;
  newQuote_2: PlanHelper;
  newQuote_3: PlanHelper;
  newQuote_4: PlanHelper;
  newQuote_5: PlanHelper;
}

export interface PortcallEntitlements {
  e2eFeature: EntitlementHelper;
  premiumSupport: EntitlementHelper;
  apiCalls: EntitlementHelper;
  tokens: EntitlementHelper;
}

export interface PortcallApi {
  /** Plans API for CRUD operations */
  plans: PlansManager;
  /** Features API for CRUD operations */
  features: FeaturesManager;
}

export interface PortcallClient {
  /** Individual plan helpers for quick subscription */
  plans: PortcallPlans;
  /** Individual entitlement helpers for checking access */
  entitlements: PortcallEntitlements;
  /** Meter events helper for recording usage */
  meterEvents: MeterEventsHelper;
  /** Users helper for user management */
  users: UsersHelper;
  /** Subscriptions helper for subscription management */
  subscriptions: SubscriptionsHelper;
  /** API for CRUD operations on plans, features, etc. */
  api: PortcallApi;
}

// =============================================================================
// Factory Function
// =============================================================================

/**
 * Create a typed Portcall client with your app's plans and features
 */
export function createPortcallClient(config: PortcallClientConfig): PortcallClient {
  const http = axios.create({
    baseURL: config.baseURL || "https://api.portcall.com",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": config.apiKey,
    },
  });

  return {
    plans: {
      e2eTestPlan: createE2eTestPlanPlan(http),
      proPlan: createProPlanPlan(http),
      testPlanViaApi: createTestPlanViaApiPlan(http),
      newQuote_1: createNewQuote_1Plan(http),
      newQuote_2: createNewQuote_2Plan(http),
      newQuote_3: createNewQuote_3Plan(http),
      newQuote_4: createNewQuote_4Plan(http),
      newQuote_5: createNewQuote_5Plan(http),
    },
    entitlements: {
      e2eFeature: createE2eFeatureEntitlement(http),
      premiumSupport: createPremiumSupportEntitlement(http),
      apiCalls: createApiCallsEntitlement(http),
      tokens: createTokensEntitlement(http),
    },
    meterEvents: new MeterEventsHelper(http),
    users: new UsersHelper(http),
    subscriptions: new SubscriptionsHelper(http),
    api: {
      plans: new PlansManager(http),
      features: new FeaturesManager(http),
    },
  };
}

// =============================================================================
// Default Export
// =============================================================================

export default createPortcallClient;
