/**
 * Auto-generated by Portcall CLI
 * Generated at: 2026-01-19T21:35:38.018Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npx portcall generate' to regenerate
 */

import axios, { AxiosInstance } from "axios";

// =============================================================================
// Types
// =============================================================================

export type PlanName = "clayPro" | "clayExplorer" | "clayStarter" | "clayFree";
export type PlanId = "plan_2a7bb631cf2b48eca13930375fd5de09" | "plan_f3b3634360e846818b5add19d75a32d1" | "plan_bcda09d14ce243a1858b4df1af2593e5" | "plan_336a3354f58d478c8def4494254e5ee5";
export type FeatureId = "crm_integrations" | "web_intent" | "exclude_people_company_filters" | "email_sequencing_integrations" | "webhooks" | "integrate_with_any_http_api" | "signals" | "use_your_own_api_keys" | "phone_number_enrichments" | "scheduling" | "integration_providers" | "rollover_credits" | "ai_claygent" | "exporting" | "sequencer" | "sculptor" | "people_company_searches" | "users" | "credits";

export interface PortcallClientConfig {
  apiKey: string;
  baseURL?: string;
}

export interface User {
  id: string;
  email: string;
  name?: string;
  created_at: string;
  updated_at: string;
}

export interface Subscription {
  id: string;
  user_id: string;
  plan_id: string;
  status: "active" | "canceled" | "past_due" | "trialing" | "incomplete";
  current_period_start?: string;
  current_period_end?: string;
  cancel_at_period_end?: boolean;
  created_at: string;
  updated_at: string;
}

export interface Entitlement {
  id: string;
  usage: number;
  quota: number;
  interval: string;
  enabled: boolean;
  next_reset_at?: string;
  created_at: string;
  updated_at: string;
}

export interface CheckoutSession {
  id: string;
  url: string;
  client_secret: string;
  expires_at: string;
}

export interface Plan {
  id: string;
  name: string;
  status: string;
  currency: string;
  interval: string;
  interval_count: number;
  trial_period_days: number;
}

// =============================================================================
// Constants
// =============================================================================

/**
 * All plan IDs in your Portcall app
 */
export const PLANS = {
  CLAY_PRO: "plan_2a7bb631cf2b48eca13930375fd5de09",
  CLAY_EXPLORER: "plan_f3b3634360e846818b5add19d75a32d1",
  CLAY_STARTER: "plan_bcda09d14ce243a1858b4df1af2593e5",
  CLAY_FREE: "plan_336a3354f58d478c8def4494254e5ee5",
} as const;

/**
 * All feature IDs in your Portcall app
 */
export const FEATURES = {
  CRM_INTEGRATIONS: "crm_integrations",
  WEB_INTENT: "web_intent",
  EXCLUDE_PEOPLE_COMPANY_FILTERS: "exclude_people_company_filters",
  EMAIL_SEQUENCING_INTEGRATIONS: "email_sequencing_integrations",
  WEBHOOKS: "webhooks",
  INTEGRATE_WITH_ANY_HTTP_API: "integrate_with_any_http_api",
  SIGNALS: "signals",
  USE_YOUR_OWN_API_KEYS: "use_your_own_api_keys",
  PHONE_NUMBER_ENRICHMENTS: "phone_number_enrichments",
  SCHEDULING: "scheduling",
  INTEGRATION_PROVIDERS: "integration_providers",
  ROLLOVER_CREDITS: "rollover_credits",
  AI_CLAYGENT: "ai_claygent",
  EXPORTING: "exporting",
  SEQUENCER: "sequencer",
  SCULPTOR: "sculptor",
  PEOPLE_COMPANY_SEARCHES: "people_company_searches",
  USERS: "users",
  CREDITS: "credits",
} as const;

// =============================================================================
// Plan Helper Class
// =============================================================================

class PlanHelper {
  constructor(
    private http: AxiosInstance,
    public readonly id: PlanId,
    public readonly name: string
  ) {}

  /**
   * Create a checkout session for a user to subscribe to this plan.
   * Creates the user if they don't exist.
   */
  async subscribe(
    email: string,
    options?: {
      name?: string;
      cancelUrl?: string;
      redirectUrl?: string;
    }
  ): Promise<CheckoutSession> {
    // First, find or create the user
    const user = await this.findOrCreateUser(email, options?.name);

    // Create checkout session
    const response = await this.http.post<{ data: CheckoutSession }>("/v1/checkout-sessions", {
      plan_id: this.id,
      user_id: user.id,
      cancel_url: options?.cancelUrl || `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000'}?status=canceled`,
      redirect_url: options?.redirectUrl || `${typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000'}?status=success`,
    });

    return response.data.data || response.data;
  }

  /**
   * Get details about this plan
   */
  async get(): Promise<Plan> {
    const response = await this.http.get<{ data: Plan }>(`/v1/plans/${this.id}`);
    return response.data.data || response.data;
  }

  private async findOrCreateUser(email: string, name?: string): Promise<User> {
    // Try to find existing user
    const listResponse = await this.http.get<{ data: User[] }>(`/v1/users?email=${encodeURIComponent(email)}`);
    const users = listResponse.data.data || listResponse.data || [];
    
    if (users.length > 0) {
      return users[0];
    }

    // Create new user
    const createResponse = await this.http.post<{ data: User }>("/v1/users", {
      email,
      name: name || email.split("@")[0],
    });

    return createResponse.data.data || createResponse.data;
  }
}

// =============================================================================
// Entitlement Helper Class
// =============================================================================

class EntitlementHelper {
  constructor(
    private http: AxiosInstance,
    public readonly id: FeatureId
  ) {}

  /**
   * Check if a user has this entitlement enabled
   */
  async isEnabled(userIdOrEmail: string): Promise<boolean> {
    try {
      const userId = await this.resolveUserId(userIdOrEmail);
      const entitlement = await this.get(userId);
      return entitlement.enabled;
    } catch {
      return false;
    }
  }

  /**
   * Check if a user can use this feature (alias for isEnabled)
   */
  async canUse(userIdOrEmail: string): Promise<boolean> {
    return this.isEnabled(userIdOrEmail);
  }

  /**
   * Check if a user has access to this feature (alias for isEnabled)
   */
  async hasAccess(userIdOrEmail: string): Promise<boolean> {
    return this.isEnabled(userIdOrEmail);
  }

  /**
   * Get the full entitlement details for a user
   */
  async get(userIdOrEmail: string): Promise<Entitlement> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Entitlement }>(
      `/v1/entitlements/${userId}/${this.id}`
    );
    return response.data.data || response.data;
  }

  /**
   * Get remaining quota for a metered feature
   */
  async getRemaining(userIdOrEmail: string): Promise<number> {
    const entitlement = await this.get(userIdOrEmail);
    if (entitlement.quota === -1) {
      return Infinity; // Unlimited
    }
    return Math.max(0, entitlement.quota - entitlement.usage);
  }

  /**
   * Get usage for a metered feature
   */
  async getUsage(userIdOrEmail: string): Promise<{ usage: number; quota: number; remaining: number }> {
    const entitlement = await this.get(userIdOrEmail);
    const remaining = entitlement.quota === -1 ? Infinity : Math.max(0, entitlement.quota - entitlement.usage);
    return {
      usage: entitlement.usage,
      quota: entitlement.quota,
      remaining,
    };
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    // If it looks like an email, look up the user
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Meter Events Helper Class
// =============================================================================

class MeterEventsHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Record usage for a metered feature
   */
  async record(
    userIdOrEmail: string,
    featureId: FeatureId,
    usage: number = 1
  ): Promise<void> {
    const userId = await this.resolveUserId(userIdOrEmail);
    await this.http.post("/v1/meter-events", {
      user_id: userId,
      feature_id: featureId,
      usage,
    });
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Users Helper Class
// =============================================================================

class UsersHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Get a user by email
   */
  async getByEmail(email: string): Promise<User | null> {
    const response = await this.http.get<{ data: User[] }>(
      `/v1/users?email=${encodeURIComponent(email)}`
    );
    const users = response.data.data || response.data || [];
    return users[0] || null;
  }

  /**
   * Get a user by ID
   */
  async get(userId: string): Promise<User> {
    const response = await this.http.get<{ data: User }>(`/v1/users/${userId}`);
    return response.data.data || response.data;
  }

  /**
   * Create a new user
   */
  async create(data: { email: string; name?: string }): Promise<User> {
    const response = await this.http.post<{ data: User }>("/v1/users", data);
    return response.data.data || response.data;
  }

  /**
   * Find or create a user by email
   */
  async findOrCreate(email: string, name?: string): Promise<User> {
    const existing = await this.getByEmail(email);
    if (existing) {
      return existing;
    }
    return this.create({ email, name: name || email.split("@")[0] });
  }
}

// =============================================================================
// Subscriptions Helper Class
// =============================================================================

class SubscriptionsHelper {
  constructor(private http: AxiosInstance) {}

  /**
   * Get active subscription for a user
   */
  async getActive(userIdOrEmail: string): Promise<Subscription | null> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Subscription[] }>(
      `/v1/subscriptions?user_id=${userId}&status=active&limit=1`
    );
    const subscriptions = response.data.data || response.data || [];
    return subscriptions[0] || null;
  }

  /**
   * List all subscriptions for a user
   */
  async list(userIdOrEmail: string): Promise<Subscription[]> {
    const userId = await this.resolveUserId(userIdOrEmail);
    const response = await this.http.get<{ data: Subscription[] }>(
      `/v1/subscriptions?user_id=${userId}`
    );
    return response.data.data || response.data || [];
  }

  /**
   * Cancel a subscription
   */
  async cancel(subscriptionId: string, immediately: boolean = false): Promise<Subscription> {
    const response = await this.http.post<{ data: Subscription }>(
      `/v1/subscriptions/${subscriptionId}/cancel`,
      { immediately }
    );
    return response.data.data || response.data;
  }

  /**
   * Update a subscription (e.g., change plan)
   */
  async update(subscriptionId: string, data: { plan_id?: PlanId }): Promise<Subscription> {
    const response = await this.http.post<{ data: Subscription }>(
      `/v1/subscriptions/${subscriptionId}`,
      data
    );
    return response.data.data || response.data;
  }

  private async resolveUserId(userIdOrEmail: string): Promise<string> {
    if (userIdOrEmail.includes("@")) {
      const response = await this.http.get<{ data: User[] }>(
        `/v1/users?email=${encodeURIComponent(userIdOrEmail)}`
      );
      const users = response.data.data || response.data || [];
      if (users.length === 0) {
        throw new Error(`User not found: ${userIdOrEmail}`);
      }
      return users[0].id;
    }
    return userIdOrEmail;
  }
}

// =============================================================================
// Plans Manager Class (CRUD operations)
// =============================================================================

interface CreatePlanParams {
  name: string;
  currency?: string;
  interval?: "day" | "week" | "month" | "year";
  interval_count?: number;
  trial_period_days?: number;
  unit_amount?: number;
}

interface UpdatePlanParams {
  name?: string;
  currency?: string;
  interval?: "day" | "week" | "month" | "year";
  interval_count?: number;
  trial_period_days?: number;
  unit_amount?: number;
}

interface AddFeatureParams {
  plan_id: string;
  feature_id: string;
  interval?: "day" | "week" | "month" | "year";
  quota?: number;
}

interface PlanFeature {
  id: string;
  feature?: string;
  interval?: string;
  quota?: number;
  created_at: string;
  updated_at: string;
}

class PlansManager {
  constructor(private http: AxiosInstance) {}

  /**
   * List all plans
   */
  async list(): Promise<Plan[]> {
    const response = await this.http.get<{ data: Plan[] }>("/v1/plans");
    return response.data.data || response.data || [];
  }

  /**
   * Get a plan by ID
   */
  async get(planId: string): Promise<Plan> {
    const response = await this.http.get<{ data: Plan }>(`/v1/plans/${planId}`);
    return response.data.data || response.data;
  }

  /**
   * Create a new plan
   */
  async create(data: CreatePlanParams): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>("/v1/plans", data);
    return response.data.data || response.data;
  }

  /**
   * Update a plan
   */
  async update(planId: string, data: UpdatePlanParams): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>(`/v1/plans/${planId}`, data);
    return response.data.data || response.data;
  }

  /**
   * Publish a plan (make it available for subscriptions)
   */
  async publish(planId: string): Promise<Plan> {
    const response = await this.http.post<{ data: Plan }>(`/v1/plans/${planId}/publish`, {});
    return response.data.data || response.data;
  }

  /**
   * Add a feature to a plan
   */
  async addFeature(data: AddFeatureParams): Promise<PlanFeature> {
    const response = await this.http.post<{ data: PlanFeature }>("/v1/plan-features", data);
    return response.data.data || response.data;
  }

  /**
   * List features for a plan
   */
  async listFeatures(planId: string): Promise<PlanFeature[]> {
    const response = await this.http.get<{ data: PlanFeature[] }>(`/v1/plan-features?plan_id=${planId}`);
    return response.data.data || response.data || [];
  }
}

// =============================================================================
// Features Manager Class (CRUD operations)
// =============================================================================

interface CreateFeatureParams {
  feature_id: string;
  is_metered?: boolean;
}

interface Feature {
  id: string;
  is_metered: boolean;
  created_at: string;
  updated_at: string;
}

class FeaturesManager {
  constructor(private http: AxiosInstance) {}

  /**
   * List all features
   */
  async list(params?: { is_metered?: boolean }): Promise<Feature[]> {
    let url = "/v1/features";
    if (params?.is_metered !== undefined) {
      url += `?is_metered=${params.is_metered}`;
    }
    const response = await this.http.get<{ data: Feature[] }>(url);
    return response.data.data || response.data || [];
  }

  /**
   * List all non-metered (boolean) features
   */
  async listStandard(): Promise<Feature[]> {
    return this.list({ is_metered: false });
  }

  /**
   * List all metered features
   */
  async listMetered(): Promise<Feature[]> {
    return this.list({ is_metered: true });
  }

  /**
   * Create a new feature
   */
  async create(data: CreateFeatureParams): Promise<Feature> {
    const response = await this.http.post<{ data: Feature }>("/v1/features", data);
    return response.data.data || response.data;
  }
}

// =============================================================================
// Generated Plan Helpers
// =============================================================================

/**
 * Clay Pro plan helper
 * ID: plan_2a7bb631cf2b48eca13930375fd5de09
 * Status: published
 */
function createClayProPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_2a7bb631cf2b48eca13930375fd5de09", "Clay Pro");
}

/**
 * Clay Explorer plan helper
 * ID: plan_f3b3634360e846818b5add19d75a32d1
 * Status: published
 */
function createClayExplorerPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_f3b3634360e846818b5add19d75a32d1", "Clay Explorer");
}

/**
 * Clay Starter plan helper
 * ID: plan_bcda09d14ce243a1858b4df1af2593e5
 * Status: published
 */
function createClayStarterPlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_bcda09d14ce243a1858b4df1af2593e5", "Clay Starter");
}

/**
 * Clay Free plan helper
 * ID: plan_336a3354f58d478c8def4494254e5ee5
 * Status: published
 */
function createClayFreePlan(http: AxiosInstance) {
  return new PlanHelper(http, "plan_336a3354f58d478c8def4494254e5ee5", "Clay Free");
}

// =============================================================================
// Generated Entitlement Helpers  
// =============================================================================

/**
 * crm_integrations entitlement helper
 * Metered: false
 */
function createCrmIntegrationsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "crm_integrations");
}

/**
 * web_intent entitlement helper
 * Metered: false
 */
function createWebIntentEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "web_intent");
}

/**
 * exclude_people_company_filters entitlement helper
 * Metered: false
 */
function createExcludePeopleCompanyFiltersEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "exclude_people_company_filters");
}

/**
 * email_sequencing_integrations entitlement helper
 * Metered: false
 */
function createEmailSequencingIntegrationsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "email_sequencing_integrations");
}

/**
 * webhooks entitlement helper
 * Metered: false
 */
function createWebhooksEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "webhooks");
}

/**
 * integrate_with_any_http_api entitlement helper
 * Metered: false
 */
function createIntegrateWithAnyHttpApiEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "integrate_with_any_http_api");
}

/**
 * signals entitlement helper
 * Metered: false
 */
function createSignalsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "signals");
}

/**
 * use_your_own_api_keys entitlement helper
 * Metered: false
 */
function createUseYourOwnApiKeysEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "use_your_own_api_keys");
}

/**
 * phone_number_enrichments entitlement helper
 * Metered: false
 */
function createPhoneNumberEnrichmentsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "phone_number_enrichments");
}

/**
 * scheduling entitlement helper
 * Metered: false
 */
function createSchedulingEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "scheduling");
}

/**
 * integration_providers entitlement helper
 * Metered: false
 */
function createIntegrationProvidersEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "integration_providers");
}

/**
 * rollover_credits entitlement helper
 * Metered: false
 */
function createRolloverCreditsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "rollover_credits");
}

/**
 * ai_claygent entitlement helper
 * Metered: false
 */
function createAiClaygentEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "ai_claygent");
}

/**
 * exporting entitlement helper
 * Metered: false
 */
function createExportingEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "exporting");
}

/**
 * sequencer entitlement helper
 * Metered: false
 */
function createSequencerEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "sequencer");
}

/**
 * sculptor entitlement helper
 * Metered: false
 */
function createSculptorEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "sculptor");
}

/**
 * people_company_searches entitlement helper
 * Metered: true
 */
function createPeopleCompanySearchesEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "people_company_searches");
}

/**
 * users entitlement helper
 * Metered: true
 */
function createUsersEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "users");
}

/**
 * credits entitlement helper
 * Metered: true
 */
function createCreditsEntitlement(http: AxiosInstance) {
  return new EntitlementHelper(http, "credits");
}

// =============================================================================
// Main Client Types
// =============================================================================

export interface PortcallPlans {
  clayPro: PlanHelper;
  clayExplorer: PlanHelper;
  clayStarter: PlanHelper;
  clayFree: PlanHelper;
}

export interface PortcallEntitlements {
  crmIntegrations: EntitlementHelper;
  webIntent: EntitlementHelper;
  excludePeopleCompanyFilters: EntitlementHelper;
  emailSequencingIntegrations: EntitlementHelper;
  webhooks: EntitlementHelper;
  integrateWithAnyHttpApi: EntitlementHelper;
  signals: EntitlementHelper;
  useYourOwnApiKeys: EntitlementHelper;
  phoneNumberEnrichments: EntitlementHelper;
  scheduling: EntitlementHelper;
  integrationProviders: EntitlementHelper;
  rolloverCredits: EntitlementHelper;
  aiClaygent: EntitlementHelper;
  exporting: EntitlementHelper;
  sequencer: EntitlementHelper;
  sculptor: EntitlementHelper;
  peopleCompanySearches: EntitlementHelper;
  users: EntitlementHelper;
  credits: EntitlementHelper;
}

export interface PortcallApi {
  /** Plans API for CRUD operations */
  plans: PlansManager;
  /** Features API for CRUD operations */
  features: FeaturesManager;
}

export interface PortcallClient {
  /** Individual plan helpers for quick subscription */
  plans: PortcallPlans;
  /** Individual entitlement helpers for checking access */
  entitlements: PortcallEntitlements;
  /** Meter events helper for recording usage */
  meterEvents: MeterEventsHelper;
  /** Users helper for user management */
  users: UsersHelper;
  /** Subscriptions helper for subscription management */
  subscriptions: SubscriptionsHelper;
  /** API for CRUD operations on plans, features, etc. */
  api: PortcallApi;
}

// =============================================================================
// Factory Function
// =============================================================================

/**
 * Create a typed Portcall client with your app's plans and features
 */
export function createPortcallClient(config: PortcallClientConfig): PortcallClient {
  const http = axios.create({
    baseURL: config.baseURL || "https://api.portcall.com",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": config.apiKey,
    },
  });

  return {
    plans: {
      clayPro: createClayProPlan(http),
      clayExplorer: createClayExplorerPlan(http),
      clayStarter: createClayStarterPlan(http),
      clayFree: createClayFreePlan(http),
    },
    entitlements: {
      crmIntegrations: createCrmIntegrationsEntitlement(http),
      webIntent: createWebIntentEntitlement(http),
      excludePeopleCompanyFilters: createExcludePeopleCompanyFiltersEntitlement(http),
      emailSequencingIntegrations: createEmailSequencingIntegrationsEntitlement(http),
      webhooks: createWebhooksEntitlement(http),
      integrateWithAnyHttpApi: createIntegrateWithAnyHttpApiEntitlement(http),
      signals: createSignalsEntitlement(http),
      useYourOwnApiKeys: createUseYourOwnApiKeysEntitlement(http),
      phoneNumberEnrichments: createPhoneNumberEnrichmentsEntitlement(http),
      scheduling: createSchedulingEntitlement(http),
      integrationProviders: createIntegrationProvidersEntitlement(http),
      rolloverCredits: createRolloverCreditsEntitlement(http),
      aiClaygent: createAiClaygentEntitlement(http),
      exporting: createExportingEntitlement(http),
      sequencer: createSequencerEntitlement(http),
      sculptor: createSculptorEntitlement(http),
      peopleCompanySearches: createPeopleCompanySearchesEntitlement(http),
      users: createUsersEntitlement(http),
      credits: createCreditsEntitlement(http),
    },
    meterEvents: new MeterEventsHelper(http),
    users: new UsersHelper(http),
    subscriptions: new SubscriptionsHelper(http),
    api: {
      plans: new PlansManager(http),
      features: new FeaturesManager(http),
    },
  };
}

// =============================================================================
// Default Export
// =============================================================================

export default createPortcallClient;
