// Code generated by portcall-gen. DO NOT EDIT.
// Generated at: 2026-01-22T00:00:00Z
//
// Run 'go run github.com/useportcall/portcall/sdks/go/cmd/portcall-gen generate' to regenerate.
//
// This is a sample generated file. Run the CLI to regenerate with your actual
// plans and features from your Portcall app.

package billing

// =============================================================================
// Plan IDs
// =============================================================================

// Plans contains all plan IDs in your Portcall app
var Plans = struct {
	Free string
	Pro  string
}{
	Free: "plan_free",
	Pro:  "plan_pro",
}

// Plan ID constants
const (
	PlanFree = "plan_free"
	PlanPro  = "plan_pro"
)

// =============================================================================
// Feature IDs
// =============================================================================

// Features contains all feature IDs in your Portcall app
var Features = struct {
	MaxSubscriptions string
	NumberOfUsers    string
}{
	MaxSubscriptions: "max_subscriptions",
	NumberOfUsers:    "number_of_users",
}

// Feature ID constants
const (
	FeatureMaxSubscriptions = "max_subscriptions"
	FeatureNumberOfUsers    = "number_of_users"
)

// MeteredFeatures contains only metered feature IDs
var MeteredFeatures = struct {
	MaxSubscriptions string
	NumberOfUsers    string
}{
	MaxSubscriptions: "max_subscriptions",
	NumberOfUsers:    "number_of_users",
}

// =============================================================================
// Plan Metadata
// =============================================================================

// PlanMeta contains metadata about a plan
type PlanMeta struct {
	ID              string
	Name            string
	Status          string
	Currency        string
	Interval        string
	IntervalCount   int
	TrialPeriodDays int
	IsFree          bool
}

// AllPlans contains metadata for all plans
var AllPlans = []PlanMeta{
	{ID: "plan_free", Name: "Free", Status: "published", Currency: "USD", Interval: "month", IntervalCount: 1, TrialPeriodDays: 0, IsFree: true},
	{ID: "plan_pro", Name: "Pro", Status: "published", Currency: "USD", Interval: "month", IntervalCount: 1, TrialPeriodDays: 0, IsFree: false},
}

// GetPlanMeta returns the metadata for a plan by ID
func GetPlanMeta(planID string) *PlanMeta {
	for _, p := range AllPlans {
		if p.ID == planID {
			return &p
		}
	}
	return nil
}

// GetFreePlanMeta returns the first free plan metadata, if any
func GetFreePlanMeta() *PlanMeta {
	for _, p := range AllPlans {
		if p.IsFree {
			return &p
		}
	}
	return nil
}

// =============================================================================
// Feature Metadata
// =============================================================================

// FeatureMeta contains metadata about a feature
type FeatureMeta struct {
	ID        string
	IsMetered bool
}

// AllFeatures contains metadata for all features
var AllFeatures = []FeatureMeta{
	{ID: "max_subscriptions", IsMetered: true},
	{ID: "number_of_users", IsMetered: true},
}

// GetFeatureMeta returns the metadata for a feature by ID
func GetFeatureMeta(featureID string) *FeatureMeta {
	for _, f := range AllFeatures {
		if f.ID == featureID {
			return &f
		}
	}
	return nil
}

// IsMeteredFeature returns true if the feature is metered
func IsMeteredFeature(featureID string) bool {
	meta := GetFeatureMeta(featureID)
	return meta != nil && meta.IsMetered
}
